export const mockData = [
    {
        utilityTitle: 'NFT 1',
        minRentingDurationUnits: 1,
        maxRentingDurationUnits: 10,
        collateralAmount: '100',
        rentalFeeAmount: '10',
        rentingDurationUnit: 'day',
        gracePeriodDuration: '15',
    },
    {
        utilityTitle: 'NFT 2',
        minRentingDurationUnits: 1,
        maxRentingDurationUnits: 10,
        collateralAmount: '100',
        rentalFeeAmount: '10',
        rentingDurationUnit: 'day',
        gracePeriodDuration: '15',
    },
    {
        utilityTitle: 'NFT 3',
        minRentingDurationUnits: 1,
        maxRentingDurationUnits: 10,
        collateralAmount: '100',
        rentalFeeAmount: '10',
        rentingDurationUnit: 'day',
        gracePeriodDuration: '15',
    },
    {
        utilityTitle: 'NFT 4',
        minRentingDurationUnits: 1,
        maxRentingDurationUnits: 10,
        collateralAmount: '100',
        rentalFeeAmount: '10',
        rentingDurationUnit: 'day',
        gracePeriodDuration: '15',
    },
    {
        utilityTitle: 'NFT 5',
        minRentingDurationUnits: 1,
        maxRentingDurationUnits: 10,
        collateralAmount: '100',
        rentalFeeAmount: '10',
        rentingDurationUnit: 'day',
        gracePeriodDuration: '15',
    },
    {
        utilityTitle: 'NFT 6',
        minRentingDurationUnits: 1,
        maxRentingDurationUnits: 10,
        collateralAmount: '100',
        rentalFeeAmount: '10',
        rentingDurationUnit: 'day',
        gracePeriodDuration: '15',
    },
    {
        utilityTitle: 'NFT 7',
        minRentingDurationUnits: 1,
        maxRentingDurationUnits: 10,
        collateralAmount: '100',
        rentalFeeAmount: '10',
        rentingDurationUnit: 'day',
        gracePeriodDuration: '15',
    },
];
